# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Category.create(name: "Zodiac")
Category.create(name: "Solar System")
Category.create(name: "Moon Phases")
Category.create(name: "Seasons")
Category.create(name: "Full Moons")
Category.create(name: "Days")
Category.create(name: "Ogham")
Category.create(name: "Runes")
Category.create(name: "Elements")
Category.create(name: "Directions")
Category.create(name: "Colors")
Category.create(name: "Chakras")
Category.create(name: "Misc. Plants")
Category.create(name: "Trees")
Category.create(name: "Herb & Garden")
Category.create(name: "Gemstones & Minerals")
Category.create(name: "From the Sea")
Category.create(name: "Goddesses")
Category.create(name: "Gods")
Category.create(name: "Animals")
Category.create(name: "Marine Life")
Category.create(name: "Reptiles")
Category.create(name: "Birds")
Category.create(name: "Insect & Misc.")
Category.create(name: "Magical")
Category.create(name: "Time of Day")
Category.create(name: "Tarot")
Category.create(name: "Numbers")
Category.create(name: "Celebrations")
Category.create(name: "Mythical")
Category.create(name: "Metals")
Category.create(name: "Angels")

puts "Categories seeded."
